# Generated by Django 4.1.2 on 2022-11-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='page_number',
            new_name='page_count',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
